
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-05-05T15:48:05-0400",
 "dirty": true,
 "error": null,
 "full-revisionid": "b772f2eb98b2071677f70709fe6f392cb3ece8b1",
 "version": "v0.1.4+119.gb772f2e.dirty"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
